apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data
  capacity:
    storage: 1Gi
  storageClassName: wp

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /db-data
  capacity:
    storage: 1Gi
  storageClassName: mysql